version: 2

project_name: ouch

before:
  hooks:
    - rustup default stable
    - cargo fetch --locked
    # - cargo install --locked cargo-xwin

env:
  - CROSS_CONTAINER_ENGINE=podman
  - CROSS_CONTAINER_OPTS=--platform=linux/amd64
  # - XWIN_CROSS_COMPILER=clang
  # - CXXFLAGS=-mssse3 -maes

builds:
  - builder: rust
    id: ouch
    command: build
    tool: cross
    targets:
      - x86_64-unknown-linux-gnu
      - x86_64-unknown-linux-musl
      - x86_64-apple-darwin
      - aarch64-apple-darwin
      - aarch64-unknown-linux-gnu

  # - builder: rust
  #   tool: cargo-xwin
  #   command: build
  #   flags: [--release]
  #   id: win-msvc-builds
  #   targets:
  #     - x86_64-pc-windows-msvc
  #     # - aarch64-pc-windows-msvc

archives:
  - id: ouch
    files:
      - none*
    formats: [ 'zip' ]
    allow_different_binary_count: true
    name_template: >-
      {{ .ProjectName }}_{{ .Target }}

universal_binaries:
  - replace: false

source:
  enabled: false
