name: windows-build

on:
  push:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows x86_64
            os: windows-2022
    
    steps:
    - name: rust version
      run: rustup --version
        
    - name: clone ouch repository
      run: git clone https://github.com/ouch-org/ouch

    - name: cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: build
      run: cd ouch && cargo build --release

    - name: upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: ouch
        path: target/release/ouch
