name: windows-build

on:
  push:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows x86_64
            os: windows-2022
    
    steps:
    - name: rust version
      run: rustc --version

    - name: cargo version
      run: cargo --version
        
    - name: clone ouch repository
      run: git clone https://github.com/ouch-org/ouch

    - name: cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: build
      run: cargo install ouch --git https://github.com/ouch-org/ouch

    - name: upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: ouch_Windows_x86_64.exe
        path: C:\Users\runneradmin\.cargo\bin\ouch.exe
