name: windows-build

on:
  push:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows x86_64
            os: windows-2022

    steps:
    - name: clone ouch repository
      run: git clone https://github.com/ouch-org/ouch
    
    - name: Build
      run: cd ouch && cargo build --release

    - name: Upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: ouch
        path: target/${{ matrix.BUILD_TARGET }}/ouch
